== Android

Android is the top open source project for in the mobile space, powering millions of mobile devices. But, it all started back in 2005, when a small startup called Android, Inc. was acquired by Google. With the acquisition of Android Inc, Google entered the mobile space. Later in 2007, together with other major companies, Google created the Open Handset Alliance consortium with the goal of promoting Android as a standard for mobile platforms. Today Android has taken the mobile industry by surprise with major 3rd-party handset manufacturers and network operators around the world embracing Android.  In addition, the Android ecoystem and developer community, both key elements of Android’s success, are very strong.

The future of Android looks bright. From smartphones to tablets to TVs, to home appliances and Machine-to-Machine (M2M), expect Android to power all of these, while grabbing a large segment of the mobile and embedded market. Expect Android entering the mmerging markets via low-cost, Android-powered handsets, extending the reach and business opportunities to all Android developers into markets in Africa and other emerging markets.

We have chosen a selection of popular books in this bibliography that span Android topics with the intent that you will be able to use it on your path. From basic Android core application concepts, the Java programming language on Android, to advanced topics that include advanced graphics, gaming and communications, we hope you will use these books to your advantage.
