== Intermediate-Advanced Python Development
	
=== Programming Python, Fourth Edition

_O'Reilly Media_
_By Mark Lutz_
_ISBN: 9781449398712_
_January 2011_
_$64.99 US_
_1632 pages_

Once you've come to grips with the core Python language, learning how to build Python applications presents a far more interesting challenge. Many critics consider this classic book, now updated for Python 3.x, to be the industry standard tutorial for Python application programming. With clear and concise explanations of Python syntax and programming techniques, and numerous examples that illustrate both correct usage and common idioms, this book shows you the right way to code with Python.

_http://my.safaribooksonline.com/book/programming/python/9781449398712?cid=1107-bibilio-python-link[Read it on Safari Books Online]_

=== Python Essential Reference, Fourth Edition

_Addison-Wesley Professional_
_By David M. Beazley_
_ISBN: 9780768687040_
_July 2009_
_$49.99 US_
_744 pages_

This book is the definitive reference guide to the Python programming language — the one authoritative handbook that reliably untangles and explains both the core Python language and the most essential parts of the Python library. Designed for the professional programmer, the book is concise, to the point, and highly accessible. It also includes detailed information on the Python library and many advanced subjects that is not available in either the official Python documentation or any other single reference source. Thoroughly updated to reflect the significant new programming language features and library modules that have been introduced in Python 2.6 and Python 3, this book is a guide for programmers who need to modernize existing Python code or who are planning an eventual migration to Python 3. Programmers starting a new Python project will find detailed coverage of contemporary Python programming idioms.

_http://my.safaribooksonline.com/book/programming/python/9780768687040?cid=1107-bibilio-python-link[Read it on Safari Books Online]_