Twenty years ago, Guido van Rossum was hard at work on the first release of Python. A lot has changed in those twenty years. Many of the programming languages that were contemporaries of Python have started showing their age. Meanwhile, there have been no shortages of new programming languages, yet Python continues to hold up well. Its emphasis on clean syntax, and its melding of object-oriented and functional programming elements, put it years ahead of the other popular languages from the '90s. 

The story of Python is not only about it being ahead of its time in terms of syntax and features. It is also about its open development and the community around it. Its value as a scripting language is well known, and it ships with many operating systems. For years Python has been one of the P’s in the LAMP stack used for numerous web applications. Indeed, Python’s popularity with web developers has lead to a multitude of web application frameworks written in Python: Django, TurboGears, Pylons, CherryPy, and so on. 

Even with technology's fast-moving pace, but Python remains on the cutting edge. NoSQL data stores have become increasingly popular, and you can find first class support for using Python with any of these technologies. This is just further evidence of the continued popularity of Python and the vibrant community around it. This bibliography contains a wide selection of books about Python. These range from various introductory to advanced books. Of course, web development is covered, but you might be surprised to see the wide variety of other types of development that are done using Python.

Whether you are working on machine learning or just hacking in your spare time, Python has something for you.


==================
Safari Books Online provides full access to all of the resources in this bibliography. A subscription to our “cloud library” gives you unlimited use of more than 16,000 books and videos. For a free trial, go to http://safaribooksonline.com/oscon11.
==================
